language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - echo -e "[ui]\nusername=hguser" > ~/.hgrc
  - sudo apt-get -y install mercurial
install:
  - pip install -e .
# command to run tests
script:
  - tests/run_pytest.sh
