language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - pip install codecov
  - pip install pytest-coverage
install:
  - pip install -e .
# command to run tests
script:
  - tests/run_pytest.sh --ci_coverage
after_success:
  - CODECOV_TOKEN="648eab25-7daa-445b-8bc7-d11034f464c4" codecov # submit coverage
