# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build qrm client pkg

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Version type
        options:
        - check
        - patch
        - minor
        - major
        - rc
        required: true

jobs:

  build_pkg:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
        run: |
          apt install black

    - name: build pkg
      run: |
        make ${{ github.event.inputs.version_type }}
        ls -ltrh ./dist/

#    - name: Publish a Python distribution to PyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        verbose: true
#        user: __token__
#        password: ${{ secrets.PYPI_API_TOKEN }}
#        print_hash: true
#        skip_existing: false
